name: e2e-showcase
run-name: Create all entities in Tower from end-to-end with tw_pywrap
# This workflow can be triggered manually with GitHub actions workflow dispatch button.
# It will automate the end-to-end creation all of the following entities in Nextflow Tower.

on:
  workflow_dispatch:

jobs:
  tw_pywrap_e2e_showcase:
    name:
    if: github.repository == 'seqeralabs/tw-pywrap'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    env:
      TOWER_ACCESS_TOKEN: ${{ secrets.TOWER_ACCESS_TOKEN }}
      TOWER_GITHUB_PASSWORD: ${{ secrets.TOWER_GITHUB_PASSWORD }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ASSUME_ROLE_ARN: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
      AZURE_BATCH_KEY: ${{ secrets.AZURE_BATCH_KEY }}
      AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
      GOOGLE_KEY: ${{ secrets.GOOGLE_KEY }}
      SENTIEON_LICENSE_BASE64: ${{ secrets.SENTIEON_LICENSE_BASE64 }}
    steps:
      - name: Check out source-code repository
        uses: actions/checkout@v3
        with:
          path: tw_pywrap_e2e_showcase

      - name: Check out tw-pywrap repository
        uses: actions/checkout@v3
        with:
          repository: seqeralabs/tw-pywrap
          ref: main # Latest version (for now)
          path: tw-pywrap

      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2.2.0
        with:
          auto-update-conda: true
          environment-file: tw-pywrap/environment.yml
          miniforge-variant: Mambaforge
          miniforge-version: latest
          python-version: "3.10"
          activate-environment: tw_pywrap
          use-mamba: true

      - name: Install pip & tw-pywrap
        run: |
          mamba install -y -c conda-forge pip
          pip install -e ./tw-pywrap

      - name: Create all entities on Tower from end-to-end
        run: |
          mamba init
          cd tw_pywrap_e2e_showcase
          temp_file=$(mktemp -q)
          echo $GOOGLE_KEY | base64 -d > $temp_file
          export GOOGLE_KEY=$temp_file

          tw-pywrap templates/e2e_example/tw_pywrap_e2e_showcase.yml
